apiVersion: apps/v1
kind: Deployment
metadata:
  name: config2
spec:
  selector:
    matchLabels:
      app: config2
  replicas: 1
  template:
    metadata:
      labels:
        app: config2
    spec:
      containers: 
        - name: config-service-container
          image: ashish131318/new-config-image2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
