apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-svc
spec:
  selector:
    app: config
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
      nodePort: 30080
  type: NodePort
